import { CrmIcon } from "@/features/crm/components/crm-icon";
import { getDealHealth } from "@/features/crm/utils";
import type { Deal } from "@/features/crm/types";

export function DealCard({ deal, selected, onSelect, onDragStart, onMove }: { deal: Deal; selected: boolean; onSelect: () => void; onDragStart: () => void; onMove: () => void }) {
  const health = getDealHealth(deal);
  const scoreTone = deal.score >= 80 ? "score-green" : deal.score >= 60 ? "score-amber" : "score-coral";
  return <article draggable onDragStart={onDragStart} onClick={onSelect} className={`group cursor-pointer rounded-[var(--radius)] border bg-surface p-3.5 transition-colors hover:border-[var(--accent)] ${selected ? "border-[var(--accent)] ring-1 ring-[var(--accent-soft)]" : "border-[var(--border-soft)]"}`}><div className="flex items-start justify-between gap-2"><h3 className="min-w-0 truncate text-sm font-semibold">{deal.companyName}</h3><span className={`score-ring ${scoreTone}`}>{deal.score}</span></div><p className="mt-1 font-mono text-sm font-semibold">{new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }).format(deal.value)}</p><span className="crm-service-tag">{deal.serviceName}</span><p className="mt-3 flex items-center gap-1.5 truncate text-xs text-[var(--ink-soft)]"><CrmIcon name="person" />{deal.contactName} · {deal.contactRole}</p><div className={`mt-3 flex items-center gap-1.5 text-xs ${health.tone === "coral" ? "text-[var(--coral)]" : health.tone === "amber" ? "text-[var(--amber)]" : health.tone === "neutral" ? "text-[var(--ink-faint)]" : "text-[var(--ink-soft)]"}`}><CrmIcon name="calendar" /><span>{deal.nextActivity?.scheduledAt ? health.label : "Sem atividade"}</span><button type="button" onClick={(event) => { event.stopPropagation(); onMove(); }} aria-label="Mover para próxima etapa" className="ml-auto rounded p-1 text-[var(--ink-faint)] opacity-0 transition-opacity hover:text-[var(--accent-dark)] group-hover:opacity-100">→</button><button type="button" onClick={(event) => event.stopPropagation()} aria-label="Mais opções" className="rounded p-1 text-[var(--ink-faint)] hover:text-foreground"><CrmIcon name="more" /></button></div></article>;
}
