import type { FormEvent } from "react";
import { dealStages } from "@/features/crm/constants";
import type { Deal, DealStageId } from "@/features/crm/types";

export function NewDealForm({ onSubmit, onCancel }: { onSubmit: (deal: Deal) => void; onCancel: () => void }) {
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const name = String(data.get("companyName") ?? "").trim();
    if (!name) return;
    onSubmit({ id: `deal-${Date.now()}`, companyName: name, contactName: String(data.get("contactName") ?? "Contato principal"), contactRole: String(data.get("contactRole") ?? "Decisor"), serviceName: String(data.get("serviceName") ?? "Consultoria"), value: Number(data.get("value") ?? 0), stage: String(data.get("stage") ?? "new") as DealStageId, ownerName: "João Silva", expectedCloseDate: String(data.get("expectedCloseDate") ?? "2026-09-30"), score: 70, status: "open", stageEnteredAt: "2026-09-13", createdAt: "2026-09-13", updatedAt: "2026-09-13", summary: "Novo negócio adicionado pelo pipeline." });
  }
  return <form onSubmit={submit} className="fixed inset-x-4 bottom-4 z-50 max-h-[calc(100dvh-2rem)] max-w-lg overflow-y-auto overscroll-contain rounded-[var(--radius-lg)] border border-border bg-surface p-6 shadow-2xl sm:left-auto sm:right-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-xl">Novo negócio</h2><button type="button" onClick={onCancel} aria-label="Fechar formulário" className="text-[var(--ink-soft)]">×</button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-[var(--ink-soft)] sm:col-span-2">Empresa / Prospect<input name="companyName" required className="crm-input" /></label><label className="text-xs font-semibold text-[var(--ink-soft)]">Valor<input name="value" type="number" min="0" className="crm-input" /></label><label className="text-xs font-semibold text-[var(--ink-soft)]">Serviço<input name="serviceName" defaultValue="Consultoria" className="crm-input" /></label><label className="text-xs font-semibold text-[var(--ink-soft)]">Decisor<input name="contactName" placeholder="Nome" className="crm-input" /></label><label className="text-xs font-semibold text-[var(--ink-soft)]">Cargo<input name="contactRole" placeholder="Cargo" className="crm-input" /></label><label className="text-xs font-semibold text-[var(--ink-soft)]">Etapa<select name="stage" className="crm-input">{dealStages.map((stage) => <option key={stage.id} value={stage.id}>{stage.label}</option>)}</select></label><label className="text-xs font-semibold text-[var(--ink-soft)]">Fechamento previsto<input name="expectedCloseDate" type="date" defaultValue="2026-09-30" className="crm-input" /></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-lg border border-border px-3 py-2 text-sm font-semibold">Cancelar</button><button type="submit" className="rounded-lg bg-[var(--accent)] px-3 py-2 text-sm font-semibold text-white">Adicionar negócio</button></div></form>;
}
